// print("Sensor 1: " + mouse.sensors[0].value);
// print("Sensor 2: " + mouse.sensors[1].value);
// print("Sensor 3: " + mouse.sensors[2].value);
// print("Sensor 4: " + mouse.sensors[3].value);
// print("Sensor 5: " + mouse.sensors[4].value);
// print("Sensor 6: " + mouse.sensors[5].value);
// print("Sensor 7: " + mouse.sensors[6].value);
// print("Sensor 8: " + mouse.sensors[7].value);

mouse.right_power = 1.0;
mouse.left_power = 1.0;
