wheel_base = 25.0
wheel_radius = 5.0
ticks_per_revolution = 360
max_rpm = 300.0
motor_torque = 1.0
wheel_inertia = 0.01
tire_friction = 0.8
mass = 1.0
width = 15.0
length = 25.0
gyroscope_bias= 0.01  # Small bias in rad/s
gyroscope_noise= 0.005 # Random noise in rad/s

[sensors.FRONT_RIGHT]
angle = 45.0

[sensors.FRONT_RIGHT.position_offset]
x = 12.5
y = 7.5

[sensors.FRONT_LEFT]
angle = 315.0

[sensors.FRONT_LEFT.position_offset]
x = 12.5
y = -7.5

[sensors.BACK_LEFT]
angle = 225.0

[sensors.BACK_LEFT.position_offset]
x = -12.5
y = -7.5

[sensors.BACK_RIGHT]
angle = 135.0

[sensors.BACK_RIGHT.position_offset]
x = -12.5
y = 7.5

[sensors.FRONT]
angle = 0.0

[sensors.FRONT.position_offset]
x = 20.0
y = 0.0
